### ISSUE TITLE
I have an error when I use the Sequence 2 video generation :  Error opening input: No such file or directory

### ISSUE THREAD

**Issue by Guldano** [NextDiffusion/next-view#1]
Hi,

When I try to use the Image Sequence 2 video I have an error. 
I got those lines in the webui = 

```
ffmpeg version 2023-06-21-git-1bcb8a7338-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58. 13.101 / 58. 13.101
  libavcodec     60. 21.100 / 60. 21.100
  libavformat    60.  9.100 / 60.  9.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  8.102 /  9.  8.102
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
[image2 @ 00000176556757c0] Could find no file with path 'C:\Users\***\stable\stable-diffusion-webui\extensions\next-view\output_image_batch/frame_%04d.png' and index in the range 1-5
[in#0 @ 0000017655675640] Error opening input: No such file or directory
Traceback (most recent call last):
  File "C:\Users\***\stable\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\***\stable\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\***\stable\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1335, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\***\stable\stable-diffusion-webui\venv\lib\site-packages\gradio\components\video.py", line 281, in postprocess
    processed_files = (self._format_video(y), None)
  File "C:\Users\***\stable\stable-diffusion-webui\venv\lib\site-packages\gradio\components\video.py", line 355, in _format_video
    video = self.make_temp_copy_if_needed(video)
  File "C:\Users\***\stable\stable-diffusion-webui\venv\lib\site-packages\gradio\components\base.py", line 226, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "C:\Users\***\stable\stable-diffusion-webui\venv\lib\site-packages\gradio\components\base.py", line 190, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\***\\stable\\stable-diffusion-webui\\extensions\\next-view\\output_videos\\output_video_20231016192604.mp4'

```
I followed the guide to install ffmpeg so I'm not sure the issue is about that. Any idea what went wrong ?

**Comment by Guldano** [comment]
Nevermind.. I had the option "Add number to filename when saving" in "saving images" settings

I'll try to generate the img2img batch without the option, if it works I'll Close this issue
