### ISSUE TITLE
Can't recombine the image sequence

### ISSUE THREAD

**Issue by navarisun1982** [NextDiffusion/next-view#5]
i have this error when i try to recombine the image sequence after successfully batch img2img for it

Video generated. File Location: D:\stable-diffusion-webui\extensions\next-view\output_videos\output_video_20231115003611.mp4
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1335, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\components\video.py", line 281, in postprocess
    processed_files = (self._format_video(y), None)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\components\video.py", line 355, in _format_video
    video = self.make_temp_copy_if_needed(video)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\components\base.py", line 226, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\components\base.py", line 190, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\stable-diffusion-webui\\extensions\\next-view\\output_videos\\output_video_20231115003611.mp4'

**Comment by NextDiffusion** [comment]
If my comprehension is accurate, the image sequence hasn't been transformed into a video. In such a scenario, please take the following steps:

- Confirm that the image sequence is in PNG format.
- Verify that the file names in your image sequence adhere to the specified pattern: "frame_xxxx". 
- In the Stable Diffusion UI, navigate to Settings > Saving Images/Grids > Images Filename Pattern and leave this field blank.
- Ensure that you are using the most recent version of Gradio. Go to your root stable diffusion location > open requirements.txt file > check gradio version and change to the latest (gradio>=4.3.0)

Let me know if some of these settings will help solve the problem.

Greetings, 
Next Diffusion

**Comment by navarisun1982** [comment]
@NextDiffusion that worked, thanks.
I will be having another challenge in keeping the animation stabilized, but this issue resolved
