### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by tonywhite11** [NextDiffusion/next-view#9]
I'm not sure if it's the new output folder fearure but it seems to be looking for a file before it's created. I'm not a coder though so..

Traceback (most recent call last):
  File "D:\Auto1111\webuirc\venv\Lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Auto1111\webuirc\venv\Lib\site-packages\gradio\blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Auto1111\webuirc\venv\Lib\site-packages\gradio\blocks.py", line 1335, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Auto1111\webuirc\venv\Lib\site-packages\gradio\components\video.py", line 281, in postprocess
    processed_files = (self._format_video(y), None)
                       ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Auto1111\webuirc\venv\Lib\site-packages\gradio\components\video.py", line 355, in _format_video
    video = self.make_temp_copy_if_needed(video)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Auto1111\webuirc\venv\Lib\site-packages\gradio\components\base.py", line 226, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Auto1111\webuirc\venv\Lib\site-packages\gradio\components\base.py", line 190, in hash_file
    with open(file_path, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Videos\\output_videos\\output_video_20240728174238.mp4'

**Comment by NextDiffusion** [comment]
I'm not sure what's causing the problem here. When I tested it, everything worked fine for me. Could you try deleting the "venv" folder in the Stable Diffusion directory? Afterward, please restart Stable Diffusion. This might take a little while, but it could resolve the issue.

**Comment by tonywhite11** [comment]
Thanks, I just uninstalled it.
